# Generated by Django 6.0.3 on 2026-05-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Токен подтверждения"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Email подтвержден"),
        ),
    ]
