[project]
name = "project4-mailing-service"
version = "0.1.0"
description = ""
authors = [
    { name = "Oleg Matyushenko", email = "mos_olma@mail.ru" }
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django (>=6.0.3,<7.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "psycopg2 (>=2.9.11,<3.0.0)",
    "pillow (>=12.1.1,<13.0.0)",
    "ipython (>=9.11.0,<10.0.0)"
]

[tool.poetry]
packages = [{ include = "config" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)"
]

[tool.black]
line-length = 119
extend-exclude = '''
\\.git
| \\.venv
| venv
| env
| __pycache__
'''

[tool.isort]
line_length = 119
profile = "black"
skip_glob = [".venv/*", "venv/*", "env/*", "__pycache__/*"]