# Generated by Django 6.0.3 on 2026-05-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={
                "ordering": ["-dt"],
                "permissions": [("can_view_all_attempt", "Может просматривать все попытки")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="distribution",
            options={
                "ordering": ["-end_time"],
                "permissions": [
                    ("can_view_all_distributions", "Может просматривать все рассылки"),
                    ("can_disable_distributions", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["title"],
                "permissions": [("can_view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email"],
                "permissions": [("can_view_all_recipients", "Может просматривать всех получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
